### ISSUE TITLE
[参考資料]Firebaseのドキュメント(android編)

### ISSUE THREAD

**Issue by omuomugin** [morux2/Surprizzle#3]
# Firebase storage
https://firebase.google.com/docs/storage/android/start?hl=ja

# Firebase database
https://firebase.google.com/docs/database/android/start/?hl=ja

firebase databaseだけなぜか英語だけど、leadersでやってるしよろしく！

**Comment by morux2** [comment]
storage youtube
https://www.youtube.com/watch?v=mSi7bNk4ySM
https://www.youtube.com/watch?v=Zy2DKo0v-OY
